### ISSUE TITLE
More precision in Abstract

### ISSUE THREAD

**Issue by yaronf** [ietf-wg-gnap/gnap-resource-servers#12]
Better use more concrete terms than "piece of software". Even if this creates a dependency on the Terminology section.

**Comment by fimbault** [comment]
The first sentence is shared with the core protocol : 

Core abstract = "GNAP defines a mechanism for delegating authorization to a piece of software, and conveying that delegation to the software. This delegation can include access to a set of APIs as well as information passed directly to the software."

RS extension abstract = "GNAP defines a mechanism for delegating authorization to a piece of software, and conveying that delegation to the software. This extension defines methods for resource servers (RS) to communicate with authorization servers (AS) in an interoperable fashion."

Note that by "piece of software", we actually mean "client instance". We can notice that the intro of the core spec is more detailed : "This protocol allows a piece of software, the client instance, to request delegated authorization to resource servers and to request direct information." (although direct information isn't that clear).

My proposal : 
- Align with the intro
- change also the abstract of the core protocol
