### ISSUE TITLE
Description of discovery mechanism in Intro

### ISSUE THREAD

**Issue by yaronf** [ietf-wg-gnap/gnap-resource-servers#13]
"client-facing discovery mechanism" - I'm not seeing any client-facing protocol in the document (and it wouldn't belong here anyway). This is not a typo: the rest of this sentence is an incorrect description of the discovery mechanism described in Sec. 3.1.

**Comment by aaronpk** [comment]
This section is being moved back to the core repo, tracking in ietf-wg-gnap/gnap-core-protocol#260
