### ISSUE TITLE
References to existing AT formats

### ISSUE THREAD

**Issue by yaronf** [ietf-wg-gnap/gnap-resource-servers#16]
Macaroons, Biscuits are mentioned with no references.

**Comment by aaronpk** [comment]
These token formats are not stable drafts yet, so we should make sure to revisit these references before final publication. However these would all be informative references anyway.

**Comment by fimbault** [comment]
Just a quick follow up: I talked to Geoffroy Couprie and we'll submit a proposal to IETF SEC DISPATCH, for biscuits.

**Comment by fimbault** [comment]
We now have https://www.biscuitsec.org
Still need to check with SEC DISPATCH group
