### ISSUE TITLE
What do we mean by AS discovery?

### ISSUE THREAD

**Issue by yaronf** [ietf-wg-gnap/gnap-resource-servers#17]
AS Discovery: why do we need a "well known" URI? Either we use GNAP Core to pass the AS address to the RS, and then we could pass a full URI, or we don't, and then how does the RS even know how to find the AS?

On second thought: maybe this makes sense, but should simply be renamed "AS capability discovery". I.e., you don't "discover" the AS. Once you have the AS's address, you can discover its capabilities.

Also, I'm not clear if the AS Grant URI belongs in this document.

**Comment by jricher** [comment]
It's possible that we could use the same OPTIONS request to the grant creation endpoint that the client instance uses, but then we have the problem of leaking RS-facing information and client-facing information in the response.

A thought: The client instance doesn't really :need: to do discovery with how the protocol is structured, but an RS is going to want to have a few different bits of information -- different endpoints, options, and features. It does raise an interesting question though: what if there were more of a cohesive AS-RS protocol that drove all of these interactions? An RS could then get all the other bits "inline" just like the client does. Does that even make sense, though?

**Comment by jricher** [comment]
I disagree with that reasoning -- the client-facing and rs-facing aspects of the AS are architecturally separate, and mixing them could lead to confusion. For example, if the AS advertises token formats for the RS's it protects, it implies (incorrectly) that this is information a client instance would need to care about or have any say in. While they could be in separate sections of the same document or something like that, I am personally leaning towards things being separated even more fundamentally.

**Comment by yaronf** [comment]
It's not terrible, but it would mean some information would be duplicated across the two metadata documents.

**Comment by jricher** [comment]
I believe this has been addressed by updates to section 3.1, and this issue will be closed.
