### ISSUE TITLE
RS persistent identity

### ISSUE THREAD

**Issue by yaronf** [ietf-wg-gnap/gnap-resource-servers#18]
Protecting RS requests to the AS: the RS, by definition, owns resources. This means that it needs to have a persistent identity, in addition to the (ephemeral) keys being presented. Otherwise (especially with TOFU registration) we could easily have Resource Servers squatting on other people’s resources. It is very hard to manage the mapping of RS to resources if we don't have such a persistent identity.

**Comment by jricher** [comment]
Except that the RS can only functionally manage resources that it can serve. I can claim to own a bridge and offer to sell it to you, but if you try to actually buy the bridge from me you'll come back from that meeting without a bridge. The AS in a TOFU registration is going to need to do some level of due diligence for TOFU registration of an RS, and this does need to be covered in security considerations at the very least. I don't know how much a persistent identifier helps that problem.

If we were to have the `locations` field always be a URI with strict address interpretation as hinted at by ietf-wg-gnap/gnap-core-protocol#142 and related issues, then this could have the AS do some amount of due diligence about the RS proving control of a given URL.

**Comment by yaronf** [comment]
A persistent identifier can be linked to other (implementation specific) attributes, such as contact details.

I think `locations` is too specific, and it's also difficult to prove ownership of a URI.

More generally, we should protect against bridge-sellers. I can think of various attacks such lying endpoints can mount, at the very least on privacy.

**Comment by aaronpk** [comment]
This could benefit from a formal analysis of the attack, so dropping a reference to ietf-wg-gnap/gnap-core-protocol#135 to track it there. This may also overlap with the issues described in ietf-wg-gnap/gnap-core-protocol#255
