### ISSUE TITLE
AS-RO policy delegation

### ISSUE THREAD

**Issue by fimbault** [ietf-wg-gnap/gnap-resource-servers#25]
cf discussion on [mailing list](https://mailarchive.ietf.org/arch/msg/txauth/zG86anwR55U9tzp9NPzMZnbj3ig/) and buried in ietf-wg-gnap/gnap-core-protocol#145 

The point of having an AS-RO is to allow RO to specify a policy for which of RO's access tokens should be delegated under what conditions.  AS-RS should not need to understand those policies.  The flow would be
- RO contacts AS-RS and gets one or more access tokens.
- RO delegates one or more of those tokens, potentially sub-scoped, to AS-RO.
- A different user contacts AS-RO to get a potentially sub-scoped access token from AS-RO.
- That user presents the access token delegated by AS-RO when invoking the resource.

AS-RS only needs to verify that the delegation chain is legitimate, e.g., no increase in scope, and that it grants permission for the request being made.  AS-RS does not need to understand the policy behind granting the delegation by AS-RO.

**Comment by Denisthemalice** [comment]
On March 25, I wrote a long argumentation which tooks me about half a day to write but the only comment I got was 
a thumb down from **jricher**.

I can understand that he does not agree with the text, but I would like to read his arguments.

**Comment by agropper** [comment]
@Denisthemalice I re-read the summary @fimbault https://github.com/ietf-wg-gnap/gnap-resource-servers/issues/25#issue-890213926 and it seems clear. Can you start with the one most important issue you have with that description?

**Comment by Denisthemalice** [comment]
**_@agropper_** : As said on March 25 th: 

> " there is still no definition to explain what mean the acronyms AS-RO and AS-RS" so I am unable to understand the story.

and also:

> When we will have identified the complete set of trust relationships, then we will be able to build the protocols.

A this point, I am awaiting answers from **_jricher_**.

**Comment by fimbault** [comment]
As discussed previously, there is an issue to define the trust relationships, and it seems we should now be ready to start working more on that section.

That said, we wouldn't consider the client as the most trusted part, as you have in your model @Denisthemalice

**Comment by Denisthemalice** [comment]
**_@fimbault_** : You wrote: 

> "we wouldn't consider the client as the most trusted part, as you have in your model.

The wording " most trusted part" is meaningless, since there is no graduation in trust.

**Comment by fimbault** [comment]
I was referring to your model in which the client is the central piece for privacy protection against the potential of an AS acting as "big brother". 
In that model, all clients are indeed considered more trustworthy than the AS, which is a big stretch when looking at real world attacks.

There does exist graduation in trust, although not exactly in the same way as what you're describing. See "promise theory" as a formalization (with much more nuance that just saying A trusts B for C)
