### ISSUE TITLE
Access Token Formats Negotiation

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-resource-servers#27]
In section 2. Access Token Formats, the text states:
 

> When the AS issues an access token for use at an RS, the RS needs to have some means of understanding what the access token is for in order to determine how to respond to the request. The core GNAP protocol makes no assumptions or demands on the format or contents of the access token, but such token formats can be the topic of **_agreements between the AS and RS._**

Token formats can be the topic of **_agreements between the AS and RS_** , if the AS has prior relationships with every RS.
However, it should be mentioned that the access token format can also be negotiated. Add:

> or can be negotiated by the client with the AS when the client first contacts the RS and then after the AS.

**Comment by jricher** [comment]
The negotiation is between the AS and RS, not the client. This spec is about negotiation between the AS and RS.
