### ISSUE TITLE
In section 3.4,  "token_format_required" should be changed into"token_formats_supported"

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-resource-servers#41]
In section 3.4 (Registering a Resource Set), the third field is:

> token_format_required (string): OPTIONAL. The token format required to access the identified resource. If the field is omitted, the token format is at the discretion of the AS. If the AS does not support the requested token format, the AS MUST return an error to the RS

More than one token format may be supported, in particular when there is a migration.

The third field should be changed into:

> token_formats_supported (array of strings): OPTIONAL. The token formats supported to access the identified resource. If the field is omitted, the token format is at the discretion of the AS.

**Comment by fimbault** [comment]
That is useful. 
Yet, you removed the error part. I guess that would become "If the AS does not support any of the supported token formats, the AS MUST return an error to the RS"
