### ISSUE TITLE
The privacy drawbacks when implementing an introspection service should be mentioned

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-resource-servers#5]
Section 3.3 states:

> The AS can offer an introspection service to allow an RS to validate that a given access token

The privacy impacts should be mentioned in this section, so that implementers can consider the advantages and the drawbacks
before implementing an introspection service. 

A reference to the Privacy Considerations section should also be added.

**Comment by jricher** [comment]
The privacy considerations will be expanded. Please feel free to submit additional suggested text.

**Comment by jricher** [comment]
The current draft text has a line about this. While it can always be expanded (and will be), this issue can be closed as we at least have the stub for the core issue.
