### ISSUE TITLE
Indication of token introspection for a resource

### ISSUE THREAD

**Issue by yaronf** [ietf-wg-gnap/gnap-resource-servers#63]
YS: Resource registration: the token_introspection_required element doesn't seem useful. If set to false but the AS receives an introspection call, should it reject it? If set to true and the call is not made, the AS would never know!

JR: I agree of the limited utility here, but it’s mostly telling the AS about the RS’s capabilities. Ultimately the AS is in charge of whether tokens can be introspected or not, or if they need to be.

YS: Still not convinced, suggest we remove it.

**Comment by jricher** [comment]
I believe this was addressed in #71 but not by removing it.

**Comment by yaronf** [comment]
Yes, the new sentence in #71 does address it.

Note however that we say that "an error is returned" without defining the exact error (and similarly in a few other places in the draft).

See the [core protocol](https://gnap-core-protocol-editors-draft.netlify.app/draft-ietf-gnap-core-protocol.html#name-error-response) for reference.

**Comment by jricher** [comment]
You're right, that's a gap -- we do need to define errors for the RS-facing API, we'll add that.
