### ISSUE TITLE
Trust relationships between a RS and an AS

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-resource-servers#7]
In section 5, the text states:

> The address of the GNAP endpoint MUST be sent in the "as_uri" parameter. The RS MAY additionally return a resource reference that the client instance MAY use in its access token request.

With such a sentence, it is implied that the RS can only trust a single AS. 

Since the core-protocol defines a Resource Server (RS) as "server that provides operations on protected resources, where operations require a valid access token issued by an AS" and since **_the core-protocol still does not contain any section which describes the trust relationships between the various components of the architecture_** (despite the fact that this issue that has been raised on the core-protocol), we can debate the topic for ever.

IMO, a RS can trust more than one AS and thus should be able to indicate a sequence of ASs.

**Comment by jricher** [comment]
It does not imply there is only one AS, only that the RS is simply returning a single AS for the client to talk to. This RS-driven AS-discovery protocol is intended to address the overwhelmingly common case, other discovery protocols could do different things, too. For such a multi-tiered discovery protocol to be viable, there would have to be preference order and many other security considerations built in.

**Comment by Denisthemalice** [comment]
@jricher: You are perfectly right when you write:

> For such a multi-tiered discovery protocol to be viable, there would have to be preference order and many other security considerations built in.

This is exactly what I am asking for.

To make a parallel, in the current world, when there is a request to authenticate to a web server, the user is often proposed a set of four different options to login. The same consideration should apply when a client is willing to use an API to interact with a RS.

**Comment by fimbault** [comment]
Closing as covered by core document, in trust relationships
