### ISSUE TITLE
A model where the AS and the RS do not need to establish a prior relation relationship should be able to co-exist

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-resource-servers#8]
In section 2.3.4 the text states:

> If the RS needs to, it can post a set of resources as described in the Resource Access Rights section of [I-D.ietf-gnap-core-protocol] to the AS's resource registration endpoint.

Note that the wording "AS's resource registration endpoint" is not used in the core-protocol.

Then the text states:

> The RS MUST identify itself with its own key and sign the request.

This implicitly means that the AS and the RS MUST establish a prior relation relationship. Such a sentence currently does not allow any other possibility. 

However, a model where the AS and the RS do not need to establish a prior relation relationship should be able to co-exist.

**Comment by jricher** [comment]
The core protocol does not define a resource registration endpoint, this document does. It would not be mentioned in the core.

The requirement for key presentation does not imply a requirement for prior relationship establishment by the RS any more than the same requirement placed on the client in the core document implies it there. This is already explicitly defined to allow an AS and RS that have never met.

**Comment by Denisthemalice** [comment]
When I wrote a prior relationship, I meant a relationship before the RS can receive and possibly accept an access token from a given AS. 

In the protocol that is described, the RS can indeed send a message with no key being established in advance, but for the AS to accept it, some contact must be established between the AS and the RS after that exchange.

It would even be possible to use no key at all for the RS, if the RS and the AS meet together: for example, the RS can contact the AS and they can both verify that the hash value of the sent and received message match together.

So one way or another, the AS and the RS must get in touch.

**Comment by aaronpk** [comment]
Yes, this is already possible in the current draft.

[Section 3.2](https://datatracker.ietf.org/doc/html/draft-ietf-gnap-resource-servers#section-3.2) says:

> The AS MAY require an RS to pre-register its keys or could alternatively allow calls from arbitrary keys, in a trust-on-first-use model

This allows the AS and RS to not need a pre-established relationship.

[Section 3.4](https://datatracker.ietf.org/doc/html/draft-ietf-gnap-resource-servers#section-3.4) is there explicitly to allow the RS to register resources to avoid the need for pre-established relationships.
