### ISSUE TITLE
Capabilities only (i.e. actions) are supported. ACLs (i.e. attributes associated with a subject) should also be supported 

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-resource-servers#9]
The example included in section 2.3.4 is limited to the support of capabilities. 

The functionality should be extended to also support ACLs.

**Comment by fimbault** [comment]
This issue is related to the core protocol it seems, and already covered by https://github.com/ietf-wg-gnap/gnap-core-protocol/issues/244 (the label is unclear, but in the examples I tried: "attributes" or "privileges").

**Comment by aaronpk** [comment]
Closing as a duplicate of ietf-wg-gnap/gnap-core-protocol#244 and section 2.3.4 doesn't exist.
